# Generated by Django 3.2.5 on 2022-07-06 01:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(blank=True, choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave'), ('family responsibility', 'Family Responsibility Leave'), ('study', 'Study Leave'), ('maternity', 'Maternity Leave'), ('unpaid', 'Unpaid Leave')], default='annual', max_length=30, null=True, verbose_name='Leave Type')),
                ('from_date', models.DateField(default=datetime.date.today)),
                ('to_date', models.DateField(default=datetime.date.today)),
                ('reason', models.TextField(default='Not Feeling Well', max_length=1200)),
                ('department', models.CharField(blank=True, choices=[('call center', 'Call Center'), ('admin', 'Admin'), ('prelegal', 'Prelegal'), ('it', 'IT'), ('headoffice', 'Head Office'), ('hr', 'HR'), ('finace', 'Finance'), ('marketing', 'Marketing')], default='call center', max_length=60, null=True, verbose_name='Department')),
                ('leave_balance', models.CharField(blank=True, max_length=2, null=True)),
                ('number_of_days_taken', models.IntegerField(blank=True, null=True)),
                ('days_paid', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
